### Create Student
POST localhost:7075/student
Content-Type: application/json

### Create Mark
POST localhost:7075/mark
Content-Type: application/json

{
  "studentId": 12,
  "courseId": 5,
  "mark": 87
}


### Get Mark
GET localhost:7075/mark/detailed/3

### Get Mark
GET localhost:7075/mark/3

### Get By Name
GET localhost:7075/student/by-name/

### Get All
GET localhost:7075/student

### Pagination by level
GET localhost:7075/student/paginationLevel?page=1&size=6&level=2

### Student pagination
GET localhost:7075/student/pagination?page=1&size=2

### filter Mark
POST localhost:7075/mark/filter
Content-Type: application/json

{
  "mark": 80
}

### filter Student
POST localhost:7075/student/filter
Content-Type: application/json

{
  "level": 2
}

###filter Course
POST localhost:7075/course/filter
Content-Type: application/json

{
  "name": "Kotlin"
}

### Create Course
POST localhost:7075/course
Content-Type: application/json

{"name": "Android Kotlin", "price": 1600000, "duration": 6}

### All Courses
GET localhost:7075/course

### Course Pagination
GET localhost:7075/course/pagination?page=1&size=3

### Course Pagination
GET localhost:7075/course/pagination/priceBetween?page=1&size=3&from=1400000&to=1500000